### ISSUE TITLE
Module namespaced fixtures

### ISSUE THREAD

**Issue by ticktricktrack** [rdy/fixture_builder#16]
I have a class Event::Critical Error
FixtureBuilder produces a file event_critical_errors.yml

Loading the fixture in Rspec produces:

```
Unable to load event_critical_error, underlying cause No such file to load -- event_critical_error 
```

more stack_trace in here
https://gist.github.com/2888253

My guess is that it either needs to be named differently or to live in a module subfolder. I will do a bit more research on this in the next days.

Edit: David Chelimsky suggested this should go into the rails issues rather than in here. I will create a blank rails project that recreates the failure.

**Comment by thewoolleyman** [comment]
Modules are now working...
