### ISSUE TITLE
Rails 4: Accessibility into fixtures via the name appears to be broken

### ISSUE THREAD

**Issue by driedyam** [rdy/fixture_builder#25]
I just upgraded to Rails 4 and trying to continue to use accessing the fixture data from within my tests.

fixture_builder.rb
-------------------------
FixtureBuilder.configure do |fbuilder|
    fbuilder.factory do
      @admin       = FactoryGirl.create :admin_user, email: 'admin@example.com'
    end
end

The above creates:

users.yml
---------------
admin:
  id: 335
  email: admin@example.com
  <bunch of other attributes>

In spec
-----------
accessing:
users(:admin)

gives:
NoMethodError:
       undefined method `[]' for nil:NilClass

The database records are there but I can't reference them through the above convenience anymore.

**Comment by rdy** [comment]
Rails5 support fixes these issues
