### ISSUE TITLE
Rails 5 compatibility

### ISSUE THREAD

**Issue by thewoolleyman** [rdy/fixture_builder#33]
There's a few things broken under Rails 5.

I'm going to attempt to fix them in master, and do appropriate conditional checks to ensure they are backward compatible with older rails versions.

However, please let me know here if I do break something in older versions.

-- Chad

**Comment by thewoolleyman** [comment]
This is one fix - I didn't fully test, but I THINK it should be safe, since a symbol should cast to a string if needed.  This is actually deprecated in Rails 4 as well:

https://github.com/rdy/fixture_builder/commit/d229c9160a16efd594398726deaeb9e9041d35be

**Comment by thewoolleyman** [comment]
Here's the other one:

https://github.com/rdy/fixture_builder/commit/b2e4f37915bb920ab58ea8bd3d1c788c029c3b39

Seems to be working after these two fixes, let me know of any problems...

**Comment by thewoolleyman** [comment]
One more fix for this, `cast` was the wrong method, should use `serialize`, otherwise you get an object representation in the yaml:

https://github.com/rdy/fixture_builder/commit/b2478fe4e8c491ef15556da3957804b9d1cf929a

**Comment by amilligan** [comment]
@rdy Thoughts on cutting a new gem version, with Chad's changes?

**Comment by rdy** [comment]
@amilligan @thewoolleyman i made chad a maintainer so he should feel free to do so whenever he likes.

**Comment by thewoolleyman** [comment]
Sure, we can cut a gem.  Maybe we should make a new major version, so it's easy for people to hold back if it breaks them.  Perhaps bump it to 5 so it's in sync with the corresponding Rails major version?

**Comment by thewoolleyman** [comment]
@rdy I've got a release candidate ready to push but I'm not an owner on the repo so I can't push it to rubygems.org.  I think you need to make me an owner, not just a collaborator?  Or whatever Stevenson has...

**Comment by rdy** [comment]
I'll look into it, I may not have permission on ruby gems to modify it.

**Comment by thewoolleyman** [comment]
Any word?  We have to get some way to publish it.

**Comment by rdy** [comment]
@thewoolleyman you have publishing powers now, i was having some issues with me password on rubygems, apologies.

**Comment by SuperTux88** [comment]
What is the current state of releasing a stable 0.5.0 version on rubygems? I use the rc1 from git now (and it works), but I would rather use a released version from rubygems.

**Comment by thewoolleyman** [comment]
Hey, I was able to push a release candidate now.  Sorry, forgot to re-try.

Give it a try, and if it's stable I can push a final version:

https://rubygems.org/gems/fixture_builder/versions/0.5.0.pre.RC1

**Comment by SuperTux88** [comment]
Thanks for your fast response 👍 

I use the RC1 from rubygems now, and [everything still works](https://travis-ci.org/diaspora/diaspora_federation/builds/173434213) :)

**Comment by thewoolleyman** [comment]
Great.  I'll try it on a few of my older and newer apps when I get time, and if it looks good I'll do an official release.  

Reopening this issue until I do.

Poke me if I forget :)

**Comment by thewoolleyman** [comment]
Just pushed 0.5.0, closing this out.  

Also did a major README rewrite and expansion.
