### ISSUE TITLE
CI build is failing on new travis infrastructure

### ISSUE THREAD

**Issue by thewoolleyman** [rdy/fixture_builder#34]
That's the only reason I can see why https://travis-ci.org/rdy/fixture_builder/builds/95097542 failed but https://travis-ci.org/rdy/fixture_builder/builds/95028339 didn't.

Here's their post about the migration (which is happening right now):

https://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

I don't have time to look into it right now, but opening this issue to document...

-- Chad

**Comment by rdy** [comment]
We really should fix this right away before accepting major pull requests. If someone feels like they can do this please feel free to do so.

**Comment by thewoolleyman** [comment]
Looks like a bundler upgrade might fix it, I'll try that on a branch.
