### ISSUE TITLE
JSON(B) columns are not correctly YAMLized

### ISSUE THREAD

**Issue by A2ADev** [rdy/fixture_builder#39]
We have a JSONB column in our psql database as shown below:

```
wibble.content = { foo: bar }
```
#### Bad YAML created using fixture builder (incorrectly YAMLized as a string)

```
id: 1,
content: '{ "foo": bar" }'
```
#### Desired YAML (correctly YAMLized as a hash)

```
id: 1,
content: 
  foo: bar
```

While we were able to put together a quick monkey patch fix below we were unable to add tests because the test suite uses SQLite.

```
def serialized_value_if_needed(table_klass, attr_name, value)
  if table_klass.respond_to?(:type_for_attribute)
    if table_klass.type_for_attribute(attr_name).type == :jsonb
      value
    elsif table_klass.type_for_attribute(attr_name).respond_to?(:serialize)
      table_klass.type_for_attribute(attr_name).serialize(value)
    else
      table_klass.type_for_attribute(attr_name).type_cast_for_database(value)
    end
  else
    if table_klass.serialized_attributes.has_key? attr_name
      table_klass.serialized_attributes[attr_name].dump(value)
    else
      value
    end
  end
end
```

_Note: If we move forward with an official fix we would want to add a solution for both JSON and JSONB column types._ 

We would love to get your thoughts on making an improvement and what you see as the best path forward. 

Thanks!

**Comment by thewoolleyman** [comment]
@A2ADev If you want to submit a PR with tests for this, we can consider it.  sqlite is available for all major platforms, it shouldn't be too hard to get it going.

**Comment by thewoolleyman** [comment]
Oh, I see @basawyer already made a PR #40 .  Haven't looked closely, but we can see if we can get it green (without PG) and merge it, if the tests are good.

**Comment by thewoolleyman** [comment]
PR looked good, cherry picked, tested with PG, and merged to master without PG changes.

**Comment by jackkinsella** [comment]
I've noticed a similar issue occur with Rails 5.2, FactoryBot 4.10 when using Postgres

```ruby
# factory for Reading object
source_data { {key: 'value'} }

$ reading.source_data.class
=> Hash
```

generated readings.yml

```ruby
  source_data: '{"key": "value"}'
```
