### ISSUE TITLE
Do not delete skipped tables old yml files

### ISSUE THREAD

**Issue by Timmy72** [rdy/fixture_builder#44]
I use FixtureBuilder for some classes, and regular yml fixtures for others.

After each modification of the `db/schema.rb` file, the builder deletes all yml fixture files and rewrites the non skipped ones.

I have to checkout all fixture files to get back the regular ones and my tests pass again.

I do not see a use case where you want to delete previous yml file if you skip the corresponding table.

I just override `delete_yml_files` to fix it.

```
# Prevent deleting all non skipped files
class FixtureBuilder::Builder
  def delete_yml_files
    FileUtils.rm(*tables.map { |t| fixture_file(t) }) rescue nil
  end
end
```

**Comment by thewoolleyman** [comment]
@Timmy72 OK, I made this change!
