### ISSUE TITLE
Fixture builder looking for fixture files in the wrong location

### ISSUE THREAD

**Issue by rmeritz** [rdy/fixture_builder#47]
Fixture builder was working perfectly at version `0.5.0` but when I just upgraded to `0.5.1` it started looking for files in `test` instead of `spec` and crashing when it could not find them.

```
be rake spec:fixture_builder:rebuild                 
Automatically generated fixtures removed          
=> Building fixtures          
rake aborted!                      
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/rebecca/api/test/fixtures/about_contexts.yml
/home/rebecca/api/spec/support/fixture_builder.rb:4:in `block in <top (required)>'                               
/home/rebecca/api/spec/support/fixture_builder.rb:1:in `<top (required)>'
/home/rebecca/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/home/rebecca/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => spec:fixture_builder:rebuild => spec:fixture_builder:build
(See full trace by running task with --trace)
```

When I reverted in continued working.

**Comment by thewoolleyman** [comment]
Hi Rebecca,

Thanks for the report.

The new logic for this is here:

https://github.com/rdy/fixture_builder/blob/7b687d741a7af0c672466f32b14a0404c9696a64/lib/fixture_builder/fixtures_path.rb

You can see that if you have a `spec/fixtures` directory existing under `Rails.root`, it should find that one first, unless you've overridden `ENV['FIXTURES_PATH']`.

Do you have that directory existing, and is `ENV['FIXTURES_PATH']` unset?

**Comment by thewoolleyman** [comment]
One thing that might be happening is you don't have your `spec/fixtures` directory committed, and it somehow gets completely deleted before fixtures are built.  

If this is the case, the workaround I'd suggest is to commit a `spec/fixtures/.gitkeep` file, to ensure it always exists.

That's hacky, but I'm not sure of a more reliable way to detect which directory should be used other than its existence...

**Comment by rmeritz** [comment]
Thanks for the link to code causing the issue.

It seems like my problem is that `File.expand_path(ActiveRecord::Tasks::DatabaseTasks.fixtures_path)` returns the problematic path. 

I therefore never get into the `rescue` clause.

 I haven't figured out where/how `ActiveRecord::Tasks::DatabaseTasks.fixtures_path` is getting set. `fixtures_path` is nowhere to be found I our codebase.

I tried setting it in `spec/rails_helper.rb` with  `ActiveRecord::Tasks::DatabaseTasks.fixtures_path = File.expand_path("spec/fixtures",::Rails.root)` but I still get the same error.
