### ISSUE TITLE
Reduce diffs of regenerated fixture files

### ISSUE THREAD

**Issue by jackkinsella** [rdy/fixture_builder#51]
I've been working on a fixture dataset for my application rather rigorously in the past few days and ended up regenerating the fixtures quite often. Due to the ponderous amount of setup data I'm working with, I wanted to keep the git diffs between old and new fixtures as small as possible for my team.

Thus far, I noticed three main sources of diffs:
1. `created_at` / `updated_at` changing. My hackish solution was to freeze time with the `Timecop`gem before running the fixture_builder. If other people also have this requirement of minimal diffs I could make a PR adding a config option to set an unchanging `created_at` etc.
2. order of fixtures in each file changing. This happens because the gem's logic for building calls `.all` on `ActiveRecord` objects, but databases generally give no guarantees as to the order of records returned. This was addressable with a surgical insertion of `order(:id)` into the `builder.rb` file. I've [made a PR](https://github.com/rdy/fixture_builder/pull/50) offering this as a general solution.
3. Encrypted data (e.g. from password digests generated by `has_secure_password`). I haven't figured out a good way to stabilize this in the test environment. Would love to hear if anyone out there has a solution.

**Comment by thewoolleyman** [comment]
Sorry I never responded on this.  Anyway, we never commit these yml files, because they are derived from the underlying data.  So, it doesn't really matter if the dates or order are non-deterministic.

But the order by ID seems pretty innocuous, I'll take a look at merging it later (sorry, just cut a release for another PR, and should have looked at this one too).

**Comment by thewoolleyman** [comment]
This is now merged.  Thanks!
